image: node:18
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install pnpm -g
    - pnpm install --no-frozen-lockfile
    - pnpm run docs:build
  artifacts:
    paths:
      - public
  only:
    - main